// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: database.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string        `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Params        []*QueryParam `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryRequest) Reset() {
	*x = ExecuteQueryRequest{}
	mi := &file_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryRequest) ProtoMessage() {}

func (x *ExecuteQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteQueryRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ExecuteQueryRequest) GetParams() []*QueryParam {
	if x != nil {
		return x.Params
	}
	return nil
}

type ExecuteQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Details       string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryResponse) Reset() {
	*x = ExecuteQueryResponse{}
	mi := &file_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryResponse) ProtoMessage() {}

func (x *ExecuteQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryResponse.ProtoReflect.Descriptor instead.
func (*ExecuteQueryResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteQueryResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ExecuteQueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteQueryResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteQueryResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type QueryParam struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*QueryParam_StrValue
	//	*QueryParam_IntValue
	//	*QueryParam_UintValue
	//	*QueryParam_FloatValue
	//	*QueryParam_DoubleValue
	//	*QueryParam_BoolValue
	//	*QueryParam_BytesValue
	//	*QueryParam_TimeValue
	Value         isQueryParam_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParam) Reset() {
	*x = QueryParam{}
	mi := &file_database_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParam) ProtoMessage() {}

func (x *QueryParam) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParam.ProtoReflect.Descriptor instead.
func (*QueryParam) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{2}
}

func (x *QueryParam) GetValue() isQueryParam_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *QueryParam) GetStrValue() string {
	if x != nil {
		if x, ok := x.Value.(*QueryParam_StrValue); ok {
			return x.StrValue
		}
	}
	return ""
}

func (x *QueryParam) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*QueryParam_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *QueryParam) GetUintValue() uint64 {
	if x != nil {
		if x, ok := x.Value.(*QueryParam_UintValue); ok {
			return x.UintValue
		}
	}
	return 0
}

func (x *QueryParam) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*QueryParam_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *QueryParam) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*QueryParam_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *QueryParam) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*QueryParam_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *QueryParam) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*QueryParam_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *QueryParam) GetTimeValue() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Value.(*QueryParam_TimeValue); ok {
			return x.TimeValue
		}
	}
	return nil
}

type isQueryParam_Value interface {
	isQueryParam_Value()
}

type QueryParam_StrValue struct {
	StrValue string `protobuf:"bytes,1,opt,name=str_value,json=strValue,proto3,oneof"`
}

type QueryParam_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type QueryParam_UintValue struct {
	UintValue uint64 `protobuf:"varint,3,opt,name=uint_value,json=uintValue,proto3,oneof"`
}

type QueryParam_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,4,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type QueryParam_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,5,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type QueryParam_BoolValue struct {
	BoolValue bool `protobuf:"varint,6,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type QueryParam_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,7,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type QueryParam_TimeValue struct {
	TimeValue *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=time_value,json=timeValue,proto3,oneof"`
}

func (*QueryParam_StrValue) isQueryParam_Value() {}

func (*QueryParam_IntValue) isQueryParam_Value() {}

func (*QueryParam_UintValue) isQueryParam_Value() {}

func (*QueryParam_FloatValue) isQueryParam_Value() {}

func (*QueryParam_DoubleValue) isQueryParam_Value() {}

func (*QueryParam_BoolValue) isQueryParam_Value() {}

func (*QueryParam_BytesValue) isQueryParam_Value() {}

func (*QueryParam_TimeValue) isQueryParam_Value() {}

var File_database_proto protoreflect.FileDescriptor

const file_database_proto_rawDesc = "" +
	"\n" +
	"\x0edatabase.proto\x12\bdatabase\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"Y\n" +
	"\x13ExecuteQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12,\n" +
	"\x06params\x18\x02 \x03(\v2\x14.database.QueryParamR\x06params\"r\n" +
	"\x14ExecuteQueryResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\"\xbd\x02\n" +
	"\n" +
	"QueryParam\x12\x1d\n" +
	"\tstr_value\x18\x01 \x01(\tH\x00R\bstrValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"uint_value\x18\x03 \x01(\x04H\x00R\tuintValue\x12!\n" +
	"\vfloat_value\x18\x04 \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fdouble_value\x18\x05 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x06 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vbytes_value\x18\a \x01(\fH\x00R\n" +
	"bytesValue\x12;\n" +
	"\n" +
	"time_value\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x00R\ttimeValueB\a\n" +
	"\x05value2`\n" +
	"\x0fDatabaseService\x12M\n" +
	"\fExecuteQuery\x12\x1d.database.ExecuteQueryRequest\x1a\x1e.database.ExecuteQueryResponseBOZM/Users/stepanbezhuk/work/Beckend/ShopperBE/db-service/proto/database;databaseb\x06proto3"

var (
	file_database_proto_rawDescOnce sync.Once
	file_database_proto_rawDescData []byte
)

func file_database_proto_rawDescGZIP() []byte {
	file_database_proto_rawDescOnce.Do(func() {
		file_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_database_proto_rawDesc), len(file_database_proto_rawDesc)))
	})
	return file_database_proto_rawDescData
}

var file_database_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_database_proto_goTypes = []any{
	(*ExecuteQueryRequest)(nil),   // 0: database.ExecuteQueryRequest
	(*ExecuteQueryResponse)(nil),  // 1: database.ExecuteQueryResponse
	(*QueryParam)(nil),            // 2: database.QueryParam
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_database_proto_depIdxs = []int32{
	2, // 0: database.ExecuteQueryRequest.params:type_name -> database.QueryParam
	3, // 1: database.QueryParam.time_value:type_name -> google.protobuf.Timestamp
	0, // 2: database.DatabaseService.ExecuteQuery:input_type -> database.ExecuteQueryRequest
	1, // 3: database.DatabaseService.ExecuteQuery:output_type -> database.ExecuteQueryResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_database_proto_init() }
func file_database_proto_init() {
	if File_database_proto != nil {
		return
	}
	file_database_proto_msgTypes[2].OneofWrappers = []any{
		(*QueryParam_StrValue)(nil),
		(*QueryParam_IntValue)(nil),
		(*QueryParam_UintValue)(nil),
		(*QueryParam_FloatValue)(nil),
		(*QueryParam_DoubleValue)(nil),
		(*QueryParam_BoolValue)(nil),
		(*QueryParam_BytesValue)(nil),
		(*QueryParam_TimeValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_database_proto_rawDesc), len(file_database_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_database_proto_goTypes,
		DependencyIndexes: file_database_proto_depIdxs,
		MessageInfos:      file_database_proto_msgTypes,
	}.Build()
	File_database_proto = out.File
	file_database_proto_goTypes = nil
	file_database_proto_depIdxs = nil
}
